### ISSUE TITLE
Invalid parameter Error

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#643] opened 2014-09-29 01:22 UTC
When update server setting, Displayed Invalid parameter Error.
Reproduce
1.Add server.
2.Click "edit" button.
3.Hostname column edit.
4.Click "apply" button.
Invalid parameter Error.

**Comment by Mnakagawa** [comment] 2015-05-07 07:51
This is not a bug. So I close this issue.

**Closed by Mnakagawa** 2015-05-07 07:51 UTC
Labels: 14.09-stable
